print("What did the pig say to the cow?")
input()
print("I don't want any beef lol")
print("Want more? I got a whole dictionary full of jokes")
input()
print("I'll tell you anyway")
print()
print ("what do you call a dog that does magic?")
input()
print("A Labracadabrador")
print()
print("Now, I know that was a bad pun, but let me explain..")
print("...")
print("Basically, i just got fired at the keyboard factory, they said i wasn't putting in enough cntrl alt Shifts....")
